###############################################################################
# This source file is part of the tomviz-pipeline project.
# It is released under the 3-Clause BSD License, see "LICENSE".
###############################################################################
"""XYZ writer for Molecule port payloads.

The XYZ format is a plain-text representation of atomic positions with
one element-symbol + xyz line per atom; bonds are NOT preserved (XYZ has
no notion of them). If you need bonds, that's a future PDB/MOL writer.

  <num_atoms>
  <comment line>
  <symbol> <x> <y> <z>
  ...

Accepts the library's :class:`tomviz_pipeline.molecule.Molecule`
natively, plus vtkMolecule (duck-typed) for payloads produced by
scripts that build vtk objects directly."""

from pathlib import Path

from tomviz_pipeline.molecule import Molecule, element_symbol


def _write_molecule(molecule: Molecule, target_path: Path) -> None:
    with open(target_path, 'w') as f:
        f.write(f'{molecule.num_atoms}\n')
        f.write('Generated by tomviz-pipeline\n')
        for number, pos in zip(molecule.atomic_numbers,
                               molecule.positions):
            symbol = element_symbol(int(number))
            f.write(
                f'{symbol} {pos[0]:.6f} {pos[1]:.6f} {pos[2]:.6f}\n')


def _write_vtk_molecule(payload, target_path: Path) -> None:
    num_atoms = payload.GetNumberOfAtoms()

    with open(target_path, 'w') as f:
        f.write(f'{num_atoms}\n')
        f.write('Generated by tomviz-pipeline\n')
        for i in range(num_atoms):
            atom = payload.GetAtom(i)
            symbol = element_symbol(int(atom.GetAtomicNumber()))
            pos = atom.GetPosition()
            f.write(
                f'{symbol} {pos[0]:.6f} {pos[1]:.6f} {pos[2]:.6f}\n')


def write_molecule_xyz(payload, target_path: Path) -> None:
    """Write a Molecule (or vtkMolecule) to disk in standard XYZ
    format. Raises TypeError for unrecognized payloads."""
    if isinstance(payload, Molecule):
        _write_molecule(payload, target_path)
        return
    if (hasattr(payload, 'GetNumberOfAtoms')
            and hasattr(payload, 'GetAtom')):
        _write_vtk_molecule(payload, target_path)
        return
    raise TypeError(
        f'XYZ writer expected a Molecule, got {type(payload).__name__}')
